[project]
name=WBSys
output=build\WBSys.exe
cl=cl.exe
link=link.exe
objdir=build\obj
linkflags=/NOLOGO
;pdb=build\WBSys.pdb
message=${company}: Building ${name} ${version} (${configuration}) for ${architecture}

[variables]
company=NoJuo
version=1.0
configuration=Debug
architecture=amd64
source_root=src
include_root=include
build_root=build

[defaults]
flags=/EHsc /std:c++17
includes=include

[file:src\main.cpp]
compile_msg=[CC] Compiling ${file} -> ${object}

[file:src\builder.cpp]
compile_msg=[CC] Compiling ${file} -> ${object}

[file:src\manifest.cpp]
compile_msg=[CC] Compiling ${file} -> ${object}

[file:src\process.cpp]
compile_msg=[CC] Compiling ${file} -> ${object}

[file:src\utility.cpp]
compile_msg=[CC] Compiling ${file} -> ${object}